baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Adastral Women In Tech"
# theme = "women_in_tech"
theme = "ananke"

[params]
  background_color_class = "bg-purple"

[params.home]
  heroText = "Welcome to Adastral Women in Tech"
  about = "We are the community of women in technology based at Adastral Park"
